[package]
name = "getip-rs"
version = "0.1.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]

[dependencies]
iron = "*"
time = "*"
hyper = "*"
term = "*"

[dependencies.logger]
git = "https://github.com/iron/logger.git"
